### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by superMDguy** [scaljeri/angular-route-xxl#1]
Hi! First of all, thanks for creating this, as it's going to really simplify accessing route params in nested routes. I had a couple of feature requests, that I'd be happy to help implement, if you want. 

1. A way to access the query params. think this would just be another decorator, `@RouteQueryParams`, that's mostly the same as the other two decorators.

2. A way to access the route as a snapshot instead of as an observable.. This could just be done by subscribing to the observable of the params and data inside the component, but it'd be much simpler to just add in something like a `useSnapshot` to each decorator.

Thanks for your consideration!

**Comment by scaljeri** [comment]
Hi @superMDguy both suggestions sounds great, thnx for that! It would be great if you want to help, and create a PR!

**Comment by superMDguy** [comment]
Ok, thanks.
