### ISSUE TITLE
AoT compilation error

### ISSUE THREAD

**Issue by vporoshok** [scaljeri/angular-route-xxl#4]
On compilation with aot flag I've got next error:
```
ERROR in Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 3:22 in the original .ts file), resolving symbol RouteData
```
How to fix it?

**Comment by scaljeri** [comment]
Check, I see it too, damn! I'm not sure what exactly is casing it, but I think it has to do with the nested functions inside the decorator factory. Anyway. next week I have time to fix this, until then don't use the `--aot` option!

**Comment by scaljeri** [comment]
I just pushed version 1.2.2. Can you confirm that the AOT error is gone?

**Comment by vporoshok** [comment]
There is no `d.ts` file in npm bundle. I can't import anything from package.

**Comment by scaljeri** [comment]
I see, I removed all the `ts` files, but shouldn't have removed `index.d.ts` :) Its fixed! (v1.2.3)

**Comment by vporoshok** [comment]
Build fine, but looks like decorators not work. I've using it's with `{ observable: false }` and got `undefined` with AOT. With JIT everything work

**Comment by scaljeri** [comment]
I found the problem, the component needs to implement `ngOnInit`. If you don't, AOT makes sure this hook is never called, meaning the decoratort will never run. For now, angular doesn't have a solution for this problem other than implementing an empty `ngOnIt`.

**Comment by vporoshok** [comment]
Thank you! With empty `ngOnInit` everything work fine!
