### ISSUE TITLE
Using inside Route Guards

### ISSUE THREAD

**Issue by mamsoudi** [scaljeri/angular-route-xxl#9]
I installed the latest version and now I'm wondering how can I use it inside one of my route guards and not in a component.
I have a situation that I need to access `username` param in my router even in children of the route I've specified `username` param in. 

I have access to `username` in the following route using `route.params.username` in which `route` is an instance of `ActivatedRouteSnapshot`.
`http://sth/#/pages/company/:username`

Now If I head to `http://sth/#/pages/company/:username/profile` my guard stops working since I'm in another activated route and this time I should be using `route.parent.params.username`.

Since guards supposed to be singletons I can't do `.parent.parent.parent` each time I go inside another child route. So how can I use your module inside my route guard?

**Comment by scaljeri** [comment]
I think a small change is required to fix this for route guards. Could you make a simple [https://stackblitz.com](https://stackblitz.com) of what use-case you have in mind?

**Comment by scaljeri** [comment]
Due to inactivity here I'm going to close this issue
